"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-19

Creates all nine v1 tables. Written explicitly (not autogenerated) so the
initial schema is reviewable and stable.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("app_env", sa.String(length=32), nullable=False, server_default="dev"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_dir", sa.String(length=512), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "raw_pages",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("run_id", sa.Integer(), sa.ForeignKey("scrape_runs.id"), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("requested_url", sa.String(length=1024), nullable=False),
        sa.Column("final_url", sa.String(length=1024), nullable=False),
        sa.Column("http_ok", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("visible_text", sa.Text(), nullable=False),
        sa.Column("screenshot_path", sa.String(length=512), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("content_len", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_raw_pages_run_id", "raw_pages", ["run_id"])
    op.create_index("ix_raw_pages_content_sha256", "raw_pages", ["content_sha256"])

    op.create_table(
        "extracted_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("raw_page_id", sa.Integer(), sa.ForeignKey("raw_pages.id"), nullable=False),
        sa.Column("run_id", sa.Integer(), sa.ForeignKey("scrape_runs.id"), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("company_name", sa.String(length=256), nullable=True),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_band", sa.String(length=8), nullable=False),
        sa.Column("extraction_method", sa.String(length=24), nullable=False),
        sa.Column("source_snippet", sa.Text(), nullable=False),
        sa.Column("notes_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_extracted_items_raw_page_id", "extracted_items", ["raw_page_id"])
    op.create_index("ix_extracted_items_run_id", "extracted_items", ["run_id"])
    op.create_index("ix_extracted_items_parser_version", "extracted_items", ["parser_version"])
    op.create_index("ix_extracted_items_ticker", "extracted_items", ["ticker"])

    op.create_table(
        "recommendation_events",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("source_service", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("raw_snippet", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("extracted_item_id", sa.Integer(), sa.ForeignKey("extracted_items.id"), nullable=True),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("dedupe_key", name="uq_recommendation_events_dedupe_key"),
    )
    op.create_index("ix_recommendation_events_ticker", "recommendation_events", ["ticker"])
    op.create_index("ix_recommendation_events_source_hash", "recommendation_events", ["source_hash"])
    op.create_index("ix_recommendation_events_dedupe_key", "recommendation_events", ["dedupe_key"])

    op.create_table(
        "portfolio_targets",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("policy", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("target_weight", sa.Float(), nullable=False, server_default="0"),
        sa.Column("target_dollars", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_portfolio_targets_policy", "portfolio_targets", ["policy"])
    op.create_index("ix_portfolio_targets_ticker", "portfolio_targets", ["ticker"])

    op.create_table(
        "orders_sent",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("policy", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False, server_default="MKT"),
        sa.Column("limit_price", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="PLANNED"),
        sa.Column("is_paper", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("dry_run", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("idempotency_key", name="uq_orders_sent_idempotency_key"),
    )
    op.create_index("ix_orders_sent_ticker", "orders_sent", ["ticker"])
    op.create_index("ix_orders_sent_idempotency_key", "orders_sent", ["idempotency_key"])

    op.create_table(
        "fills",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("order_id", sa.Integer(), sa.ForeignKey("orders_sent.id"), nullable=True),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_paper", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_fills_order_id", "fills", ["order_id"])
    op.create_index("ix_fills_broker_order_id", "fills", ["broker_order_id"])
    op.create_index("ix_fills_ticker", "fills", ["ticker"])

    op.create_table(
        "broker_positions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("avg_cost", sa.Float(), nullable=True),
        sa.Column("market_price", sa.Float(), nullable=True),
        sa.Column("market_value", sa.Float(), nullable=True),
        sa.Column("is_paper", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_broker_positions_snapshot_at", "broker_positions", ["snapshot_at"])
    op.create_index("ix_broker_positions_ticker", "broker_positions", ["ticker"])

    op.create_table(
        "audit_flags",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("run_id", sa.Integer(), sa.ForeignKey("scrape_runs.id"), nullable=True),
        sa.Column("flag_type", sa.String(length=48), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context_json", sa.Text(), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_audit_flags_run_id", "audit_flags", ["run_id"])
    op.create_index("ix_audit_flags_flag_type", "audit_flags", ["flag_type"])


def downgrade() -> None:
    op.drop_table("audit_flags")
    op.drop_table("broker_positions")
    op.drop_table("fills")
    op.drop_table("orders_sent")
    op.drop_table("portfolio_targets")
    op.drop_table("recommendation_events")
    op.drop_table("extracted_items")
    op.drop_table("raw_pages")
    op.drop_table("scrape_runs")
